export const registers = [
    {
        id: 1,	
        name: 'Ahamd Ekstrom',
        img: '/src/Auth/assets/p1.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: ''
    },
    {
        id: 2,	
        name: 'Steve Vaccaro',
        img: '/src/Auth/assets/p2.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 3,	
        name: 'Tiana Kenter',
        img: '/src/Auth/assets/p3.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 4,	
        name: 'Anika Levin',
        img: '/src/Auth/assets/p4.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: ''
    },
    {
        id: 5,	
        name: 'Giana Torff',
        img: '/src/Auth/assets/p5.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 6,	
        name: 'Olivia Rhye',
        img: '/src/Auth/assets/p6.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 7,	
        name: 'Ahamd Ekstrom',
        img: '/src/Auth/assets/p7.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 8,	
        name: 'Steve Vaccaro',
        img: '/src/Auth/assets/p1.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 9,	
        name: 'Tiana Kenter',
        img: '/src/Auth/assets/p2.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 10,	
        name: 'Anika Levin',
        img: '/src/Auth/assets/p3.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 11,	
        name: 'Giana Torff',
        img: '/src/Auth/assets/p4.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 12,	
        name: 'Olivia Rhye',
        img: '/src/Auth/assets/p5.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 13,	
        name: 'Ahamd Ekstrom',
        img: '/src/Auth/assets/p6.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 14,	
        name: 'Steve Vaccaro',
        img: '/src/Auth/assets/p7.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },    {
        id: 15,	
        name: 'Tiana Kenter',
        img: '/src/Auth/assets/p1.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },
    {
        id: 16,	
        name: 'Anika Levin',
        img: '/src/Auth/assets/p2.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    },    {
        id: 17,	
        name: 'Giana Torff',
        img: '/src/Auth/assets/p3.png',
        licenciatura: 'Licenciatura - Informatica',
        materia: 'informatica',
        grade: '4th',
        topic: 'Introduccion a POO',
        date: new Date().toLocaleDateString(),
        input: '12 : 00 : 00',
        output: '13: 00 : 00'
    }
]